### ISSUE TITLE
HMC346AMS8GE 评估版

### ISSUE THREAD

**Issue by CNLHC** [CNLHC/NUEDC-Toolbox#1]
@van-zky 作为开哥熟悉Kicad的第一个小项目吧。

7月4日前完成 [HMC346AMS8GE](https://www.analog.com/en/products/hmc346ams8ge.html)电压控制衰减器评估板的绘制，生成提交板厂的Gerber文件

**Comment by van-zky** [comment]
HMC346AMS8GE测评板PCB已上传至toolbox
(3d0909e8b9aa7e2cceda35034dc724f12b9f9c63)

**Comment by CNLHC** [comment]
@NPEIGHT 冠华帮忙Review一下吧，看看有没有问题，没问题的话准备出Gerber先打一版。

**Comment by NPEIGHT** [comment]
已经嘉立创下单，高端亚黑工艺制造

**Comment by van-zky** [comment]
改进的评估版上午已重新发往厂家打印

**Comment by van-zky** [comment]
模块测试完毕，测试文档已上传
