### ISSUE TITLE
SPI集线器制作

### ISSUE THREAD

**Issue by CNLHC** [CNLHC/NUEDC-Toolbox#21]
制作SPI集线器，将SCK，MOSI，MISO引出。

考虑时钟极性和锁存边沿，一共引出四组总线。

此外考虑到部分芯片存在硬编码配置项目，请引出一组（足够多的）逻辑1和逻辑0，用于硬编码配置。

尽量充分利用10*10的线路板空间。

**Comment by van-zky** [comment]
已经过大佬review，提交工厂

**Comment by van-zky** [comment]
模块已通过测试并开始应用
